coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false

ignore:
  - "**/*_test.go"
  - "**/*.pb.go"
  - "**/*.gen.go"
  - "client.gen.go"
  - "examples/**"
  - "vendor/**"
  - "**/mocks/**"
  - "**/mock_*.go"
